### ISSUE TITLE
Repeated Roots

### ISSUE THREAD

**Issue by rodneyosodo** [smithjilks/JKUAT-MechT-4th-year-2021#1]
There is an issue with your script

![Screenshot from 2021-06-09 22-04-45](https://user-images.githubusercontent.com/28790446/121414313-2db01780-c96f-11eb-8da8-65ef5f923158.png)

**Comment by smithjilks** [comment]
Thank you. I'll look into it and correct it accordingly.

**Comment by rodneyosodo** [comment]
![Screenshot from 2021-06-10 22-42-12](https://user-images.githubusercontent.com/28790446/121587408-71715280-ca3d-11eb-8e09-b9d47aa5353e.png)

**Comment by smithjilks** [comment]
Isn't the Dsolve solution an expanded form of the solution produced by the  <code> solveEquationWithRepeatedRealRoots </code> function?

**Comment by rodneyosodo** [comment]
Oh Yes

**Comment by smithjilks** [comment]
All right.
